apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-occur-restart
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: log-occur-restart
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: log-occur-restart
        selector: log-occur-restart
    spec:
      containers:
      - name: log-occur-restart
        image: hansrajrami/log-occur-restart:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "! grep -q 'Disconnecting...' /tmp/event-listener.log"
      terminationGracePeriodSeconds: 30
